# Generated by Django 4.2.16 on 2025-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_employee_organization_employee_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myapp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
